//! Compile `drivers.toml` into `generated.rs` so stock drivers stay data.
#![allow(clippy::expect_used, clippy::unwrap_used, clippy::format_push_string)]

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let src = manifest_dir.join("drivers.toml");
    println!("cargo:rerun-if-changed={}", src.display());
    let raw = fs::read_to_string(&src).expect("read drivers.toml");
    let parsed: toml::Value = toml::from_str(&raw).expect("parse drivers.toml");
    let out = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR")).join("generated.rs");
    fs::write(out, render(&parsed)).expect("write generated.rs");
}

fn render(parsed: &toml::Value) -> String {
    let mut rust = String::from(
        "// @generated by build.rs from drivers.toml. Do not edit.\n\
         use crate::driver::{Driver, Format};\n\n",
    );
    rust.push_str("pub fn stock(name: &str) -> Option<Driver> {\n    match name {\n");
    let Some(drivers) = parsed.get("drivers").and_then(toml::Value::as_table) else {
        panic!("drivers.toml missing [drivers]");
    };
    for (name, spec) in drivers {
        let format = spec
            .get("format")
            .and_then(toml::Value::as_str)
            .unwrap_or_else(|| panic!("driver {name} missing format"));
        let format_ty = match format {
            "toml" => "Format::Toml",
            "json" => "Format::Json",
            other => panic!("driver {name} unknown format {other}"),
        };
        let keys = spec
            .get("keys")
            .and_then(toml::Value::as_array)
            .unwrap_or_else(|| panic!("driver {name} missing keys"));
        let key_lits: Vec<String> = keys
            .iter()
            .map(|key| {
                let key = key.as_str().expect("key string");
                format!("\"{key}\".into()")
            })
            .collect();
        rust.push_str(&format!(
            "        \"{name}\" => Some(Driver::Path {{ format: {format_ty}, keys: vec![{}], after: None }}),\n",
            key_lits.join(", ")
        ));
    }
    rust.push_str("        _ => None,\n    }\n}\n\n");
    rust.push_str(
        "pub fn stock_keys(name: &str) -> Option<(&'static str, &'static [&'static str])> {\n    match name {\n",
    );
    for (name, spec) in drivers {
        let format = spec.get("format").and_then(toml::Value::as_str).unwrap();
        let keys = spec.get("keys").and_then(toml::Value::as_array).unwrap();
        let key_lits: Vec<String> = keys
            .iter()
            .map(|key| format!("\"{}\"", key.as_str().unwrap()))
            .collect();
        rust.push_str(&format!(
            "        \"{name}\" => Some((\"{format}\", &[{}])),\n",
            key_lits.join(", ")
        ));
    }
    rust.push_str("        _ => None,\n    }\n}\n\n");
    rust.push_str(
        "pub fn infer_name(file_name: &str) -> Option<&'static str> {\n    match file_name {\n",
    );
    let Some(names) = parsed.get("filenames").and_then(toml::Value::as_table) else {
        panic!("drivers.toml missing [filenames]");
    };
    for (file, driver) in names {
        let driver = driver.as_str().expect("filename driver");
        rust.push_str(&format!("        \"{file}\" => Some(\"{driver}\"),\n"));
    }
    rust.push_str("        _ => None,\n    }\n}\n");
    rust
}
